# configs/hotpotqa.yaml
# Settings for HotpotQA

dataset_path: "data/benchmarks/hotpotqa/test.jsonl" 
dataset_loader: "load_hotpotqa" 
metrics: ["em", "f1"] 

corpus_path: "data/corpus/wiki18_100w.jsonl"
graph_path: "data/graphs/wiki18_100w_rebel_large_graph.json"
processed_docs_path: "data/graphs/wiki18_100w_rebel_large_docs.json"
bm25_index_path: "data/graphs/wiki18_100w_bm25s_index/"
node_index_path: "data/graphs/wiki18_100w_bm25s_node_index/"
edge_index_path: "data/graphs/wiki18_100w_bm25s_edge_index/"
chunk_index_path: "data/graphs/wiki18_100w_bm25s_chunk_index/"
