# configs/nq.yaml
# Settings for Natural Questions

dataset_path: "data/benchmarks/nq/test.jsonl" 
dataset_loader: "load_nq" 
metrics: ["em", "f1"] 


corpus_path: "data/corpus/wiki18_100w.jsonl"
graph_path: "data/graphs/wiki18_100w.graph.json"
processed_docs_path: "data/graphs/wiki18_100w.docs.json"
#bm25_index_path: "data/indices/wiki18_100w.bm25.pkl"
bm25_index_path: "data/graphs/wiki18_100w_bm25s_index/"