# configs/triviaqa.yaml
# Settings for TriviaQA

# --- Benchmark Data ---
dataset_path: "data/benchmarks/triviaqa/test.jsonl" 
dataset_loader: "load_triviaqa" 
metrics: ["em", "f1"] 

# --- Knowledge Source ---
# This benchmark will use the 'wikipedia_dpr' graph and corpus
corpus_path: "data/corpus/wiki18_100w.jsonl"
graph_path: "data/graphs/wiki18_100w.graph.json"
processed_docs_path: "data/graphs/wiki18_100w.docs.json"
#bm25_index_path: "data/indices/wiki18_100w.bm25.pkl"
bm25_index_path: "data/graphs/wiki18_100w_bm25s_index/"